String validation backend
hack4impact-uiuc/memberdb-tool pull request #54
Opened 2021-03-02 18:07 UTC by Leundai

## Summary

Description of PR here...

## Changes

- Item 1
- Item 2
- Item 3

## Screenshots

(Insert image, only for frontend)

## Requests / Responses 

**Request**
(Only for backend)
POST `/api/users` Returns a list of users

```
{
  "data": {
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "password": "hellopassword"
    }
  },
  "type": "users"
}
```

**Response**
(Only for backend)
HTTP/1.1 200 OK

```
{
  "data": {
    "type": "users",
    "id": "4",
    "attributes": {
      "name": "The Dude",
      "email": "thedudeabides@wee.net",
      "last-logged-in": null,
      "created-at": "2016-10-20T17:45:08.190Z",
      "updated-at": "2016-10-20T17:45:08.190Z"
    },
    "links": {
      "self": "/users/4"
    }
  }
}
```

Closes #85, Closes #22

2021-03-06 21:26 UTC, daniel-moon32 approved these changes
Looks good!

2021-03-06 21:32 UTC, SirajChokshi requested changes
Looks good, few comments :)

2021-03-06 21:32 UTC, SirajChokshi commented on api/src/utils/user-utils.js
> +const validateField = (field, value) => {
For this function lets consider decoupling it from our global state. I would be more modular to pass in the validation fields along with our other arguments.

2021-03-06 21:32 UTC, SirajChokshi commented on api/src/utils/user-utils.js
> +  phone: /^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$/,
This query allows for phone numbers in a variety of formats (978754-5343, 978.754-5343, etc). Should we instead decide to enforce a 10 digit sequence and splice out delimiters like spaces, hyphens, and `.`'s on the frontend? This way we can also enforce a standardized format as well as one that better guarantees legitimate phone numbers.

e.g. User enters `555-545-7565` on the frontend and it gets sent to the API as `5555457565` and validated as such

2021-03-27 20:40 UTC, SirajChokshi approved these changes
Great work!

2021-03-28 08:13 UTC, merged